import BN = require('bn.js');
import { Summary } from '../index';
import { Cipher, CurvePoint } from './index';
export declare const yesVote: any;
export declare const noVote: any;
export declare const generateYesVote: (pk: string | CurvePoint) => Cipher;
export declare const generateNoVote: (pk: string | CurvePoint) => Cipher;
export declare const generateBaseVote: (pk: string | CurvePoint) => Cipher;
export declare const addVotes: (votes: Cipher[], pk: string | CurvePoint) => Cipher;
export declare const findPoint: (point: CurvePoint) => number;
export declare const tallyVotes: (pk: string, sk: BN, votes: Cipher[]) => number;
export declare const getSummary: (total: number, tallyResult: number) => Summary;
