import BN = require('bn.js');
import { Cipher, SystemParameters } from './index';
export declare const encodeMessage: (m: number | BN, sysParams: SystemParameters) => BN;
export declare const decodeMessage: (mh: number | BN, sysParams: SystemParameters) => BN;
export declare const encrypt: (message: number | BN, sysParams: SystemParameters, publicKey: BN, log?: boolean) => Cipher;
export declare const decrypt1: (cipherText: Cipher, sk: BN, sysParams: SystemParameters, log?: boolean) => BN;
export declare const decrypt2: (cipherText: Cipher, sk: BN, sysParams: SystemParameters, log?: boolean) => BN;
export declare const add: (em1: Cipher, em2: Cipher, sysParams: SystemParameters) => Cipher;
export declare const decryptShare: (params: SystemParameters, cipher: Cipher, secretKeyShare: BN) => BN;
export declare const combineDecryptedShares: (params: SystemParameters, cipher: Cipher, decryptedShares: BN[]) => BN;
